services:
  db:
    image: postgres:16
    container_name: crud_users_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crud_users_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build: .
    container_name: crud_users_api
    environment:
      PORT: 3015
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: crud_users_db
    ports:
      - "3015:3015"
    depends_on:
      - db

volumes:
  postgres_data: